In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, mean_squared_error, accuracy_score

# Linear Regression

In [19]:
from sklearn.datasets import load_boston

In [26]:
data = load_boston()
X = data.data
y = data.target

In [28]:
X.shape, y.shape

((506, 13), (506,))

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [31]:
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [34]:
lm.intercept_ , lm.coef_

(33.388062189324316,
 array([-1.28060398e-01,  3.77955693e-02,  5.86107797e-02,  3.24007007e+00,
        -1.62222676e+01,  3.89352244e+00, -1.27879944e-02, -1.42326864e+00,
         2.34513082e-01, -8.20261127e-03, -9.29950535e-01,  1.19151410e-02,
        -5.48489997e-01]))

In [36]:
pred = lm.predict(X_test)

In [37]:
mean_squared_error(y_test,pred)

20.747143360308847

# Logistic Regression

In [59]:
from sklearn.datasets import load_breast_cancer

In [70]:
data = load_breast_cancer()
X = data.data
y = data.target

In [71]:
X.shape, y.shape

((569, 30), (569,))

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [76]:
lm = LogisticRegression()
lm.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [77]:
pred = lm.predict(X_test)

In [82]:
print(confusion_matrix(y_test, pred))

[[ 63   4]
 [  4 117]]


In [83]:
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       0.94      0.94      0.94        67
          1       0.97      0.97      0.97       121

avg / total       0.96      0.96      0.96       188



In [85]:
accuracy_score(y_test, pred)

0.9574468085106383

# SVM

In [12]:
from sklearn import svm
from sklearn.datasets import load_iris

In [13]:
data = load_iris()
X = data.data
y = data.target

In [14]:
X.shape, y.shape

((150, 4), (150,))

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
model_SVM = svm.SVC(kernel='linear', C=0.1)
model_SVM.fit(X_train, y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
pred_train_SVM = model_SVM.predict(X_train)
pred_test_SVM = model_SVM.predict(X_test)

In [18]:
print('Train accuracy: {}'.format(accuracy_score(y_train,pred_train_SVM)))
print('Test accuracy: {}'.format(accuracy_score(y_test,pred_test_SVM)))

Train accuracy: 0.97
Test accuracy: 1.0


In [19]:
print(confusion_matrix(y_test,pred_test_SVM))

[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]


# Random Forest

In [20]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier 

In [21]:
model_RF = RandomForestClassifier(max_depth=3, random_state=0)
model_RF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [22]:
pred_train_RF = model_RF.predict(X_train)
pred_test_RF = model_RF.predict(X_test)

In [23]:
print('Train accuracy: {}'.format(accuracy_score(y_train,pred_train_RF)))
print('Test accuracy: {}'.format(accuracy_score(y_test,pred_test_RF)))

Train accuracy: 0.95
Test accuracy: 0.98


In [24]:
print(confusion_matrix(y_test,pred_test_RF))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]


# Linear Discrimant

In [25]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis


In [26]:
model_LD = LinearDiscriminantAnalysis()
model_LD.fit(X_train, y_train)

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [27]:
pred_train_LD = model_LD.predict(X_train)
pred_test_LD = model_LD.predict(X_test)

In [28]:
print('Train accuracy: {}'.format(accuracy_score(y_train,pred_train_LD)))
print('Test accuracy: {}'.format(accuracy_score(y_test,pred_test_LD)))

Train accuracy: 0.98
Test accuracy: 0.98


In [29]:
print(confusion_matrix(y_test,pred_test_LD))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]


# Ensemble bagging

In [30]:
eclf1 = VotingClassifier(estimators=[('SVM', model_SVM), ('RF', model_RF), ('LD', model_LD)], voting='hard')

In [31]:
eclf1.fit(X_train,y_train)

VotingClassifier(estimators=[('SVM', SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)), ('RF', RandomForestClassifier(bootstrap=True, clas...None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [32]:
pred_train = eclf1.predict(X_train)
pred_test = eclf1.predict(X_test)

/Users/mariavarga/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/Users/mariavarga/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [33]:
print('Train accuracy: {}'.format(accuracy_score(y_train,pred_train)))
print('Test accuracy: {}'.format(accuracy_score(y_test,pred_test)))

Train accuracy: 0.97
Test accuracy: 0.98


In [34]:
print(confusion_matrix(y_test,pred_test))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]


# Neural Network Keras

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [46]:
from keras.models import Model
from keras.layers.core import Activation,Dropout,Dense, Dropout
from keras.layers import Input
from keras.optimizers import Adam
from keras.initializers import glorot_uniform
from keras.layers.normalization import BatchNormalization
from keras.utils import np_utils
from keras.regularizers import l1,l2

In [55]:
onehot_encoder = OneHotEncoder(sparse=False)
y_r = y.reshape(-1,1)
y_onehot = onehot_encoder.fit_transform(y_r)

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.33, random_state=42)

In [94]:
def get_model(input_shape=4):
    
    inputs = Input(shape=(input_shape,))
    X = BatchNormalization()(inputs)
    #X = Dropout(0.3)(inputs)
    X = Dense(100,activation='relu')(X)
    #X = Dense(60,activation='relu',activity_regularizer=l1(0.01))(X)
    #X = Dropout(0.3)(X)
    #X = BatchNormalization()(X)
    #X = Dense(20,activation='relu')(X)
    #X = Dropout(0.5)(X)
    X = BatchNormalization()(X)
    X = Dense(3,activation='softmax')(X)
    model = Model(inputs=inputs, outputs=X)
    
    return model

In [95]:
NN = get_model()

In [96]:
NN.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
batch_normalization_11 (Batc (None, 4)                 16        
_________________________________________________________________
dense_18 (Dense)             (None, 100)               500       
_________________________________________________________________
batch_normalization_12 (Batc (None, 100)               400       
_________________________________________________________________
dense_19 (Dense)             (None, 3)                 303       
Total params: 1,219
Trainable params: 1,011
Non-trainable params: 208
_________________________________________________________________


In [103]:
opt = Adam(lr=0.00001)
NN.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

In [106]:
NN.fit(X_train, y_train, epochs=10, validation_data = (X_test, y_test),shuffle = True)

Train on 100 samples, validate on 50 samples
Epoch 1/10
100/100 [==============================] - 0s 205us/step - loss: 0.1177 - acc: 0.9600 - val_loss: 0.1141 - val_acc: 0.9800
Epoch 2/10
100/100 [==============================] - 0s 237us/step - loss: 0.1506 - acc: 0.9300 - val_loss: 0.1134 - val_acc: 0.9800
Epoch 3/10
100/100 [==============================] - 0s 282us/step - loss: 0.1325 - acc: 0.9700 - val_loss: 0.1129 - val_acc: 0.9800
Epoch 4/10
100/100 [==============================] - 0s 230us/step - loss: 0.1327 - acc: 0.9500 - val_loss: 0.1132 - val_acc: 0.9800
Epoch 5/10
100/100 [==============================] - 0s 237us/step - loss: 0.1337 - acc: 0.9500 - val_loss: 0.1128 - val_acc: 0.9800
Epoch 6/10
100/100 [==============================] - 0s 200us/step - loss: 0.1384 - acc: 0.9400 - val_loss: 0.1121 - val_acc: 0.9800
Epoch 7/10
100/100 [==============================] - 0s 213us/step - loss: 0.1169 - acc: 0.9700 - val_loss: 0.1120 - val_acc: 0.9800
Epoch 8/10
100/10

In [ ]:
from sklearn.preprocessing import normalize

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y)

# apply encoding to labels
labels = le.transform(y)

In [22]:
from keras.models import Model
from keras.layers.convolutional import Conv2D, MaxPooling2D, UpSampling2D
from keras.layers import Input, Add, concatenate, Flatten
from keras.layers.core import Dense, Dropout
from keras.optimizers import Adam, RMSprop
from keras.layers.normalization import BatchNormalization

In [2]:
import cv2
import glob
from PIL import Image
import numpy as np
from skimage.transform import resize
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
from sklearn.datasets import load_digits
from sklearn.preprocessing import OneHotEncoder
from keras.utils import np_utils
from keras.datasets import mnist

In [42]:
seed = 7
np.random.seed(seed)

In [43]:
digits = load_digits()

In [44]:
X = digits.images
y = digits.target

In [45]:
y = np_utils.to_categorical(y)

In [6]:
#onehot_encoder = OneHotEncoder(sparse=False)
#y_r = y.reshape(-1,1)
#y = onehot_encoder.fit_transform(y_r)

In [46]:
X = np.expand_dims(X,-1)
X = X/255.

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
path ='/Users/mariavarga/Documents/Blue Fairy/Papers/*'

In [15]:
fnames = glob.glob(path)

In [17]:
fnames = glob.glob('*.png')

In [18]:
fnames

['face2.png']

In [72]:
def open_resize(fname, img_sz = (480,360)):
    img = cv2.imread(fname)
    img = resize(img, img_sz)
    return img[:,:,::-1]

In [73]:
img = np.stack([open_resize(im) for im in fnames])

In [74]:
img.shape

(1, 480, 360, 3)

In [78]:
def model_archt(input_shape=(256,256,3)):
    
    inputs = Input(shape=input_shape)
    X = Conv2D(filters=40, kernel_size=3, padding='same', activation='relu')(inputs)
    X = MaxPooling2D()(X)
    X = BatchNormalization()(X)
    X = Conv2D(filters=40, kernel_size=3, padding='same', activation='relu')(X)
    X = MaxPooling2D()(X)
    X = BatchNormalization()(X)
    X = UpSampling2D()(X)
    X = Conv2D(filters=40, kernel_size=3, padding='same', activation='relu')(X)
    X = BatchNormalization()(X)
    X = UpSampling2D()(X)
    X = Conv2D(filters=40, kernel_size=3, padding='same', activation='relu')(X)
    X = BatchNormalization()(X)
    X = Conv2D(filters=10, kernel_size=1, padding='same', activation='softmax')(X)
    
    model = Model(inputs,X)
    
    return model

In [64]:
def model_archt(input_shape=(8,8,1)):
    
    inputs = Input(shape=input_shape)
    X = Conv2D(filters=50, kernel_size=3, padding='same', activation='relu')(inputs)
    X = MaxPooling2D()(X)
    X = Dropout(0.3)(X)
    X = BatchNormalization()(X)
    X = Conv2D(filters=50, kernel_size=3, padding='same', activation='relu')(X)
    X = MaxPooling2D()(X)
    X = Flatten()(X)
    X = Dense(10, activation= 'softmax')(X)
    
    model = Model(inputs,X)
    
    return model

In [65]:
model = model_archt(input_shape=(8,8,1))

In [66]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 8, 8, 1)           0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 8, 8, 50)          500       
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 4, 4, 50)          0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 4, 4, 50)          0         
_________________________________________________________________
batch_normalization_7 (Batch (None, 4, 4, 50)          200       
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 4, 4, 50)          22550     
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 2, 2, 50)          0         
__________

In [67]:
opt = Adam(lr=0.001)
model.compile(opt, loss='categorical_crossentropy', metrics=['accuracy'])

In [68]:
model.fit(X_train, y_train, batch_size=16, epochs=10, validation_data=[X_test,y_test])

Train on 1203 samples, validate on 594 samples
Epoch 1/10
1203/1203 [==============================] - 4s 3ms/step - loss: 1.8742 - acc: 0.4904 - val_loss: 1.0768 - val_acc: 0.8350
Epoch 2/10
1203/1203 [==============================] - 3s 2ms/step - loss: 0.7353 - acc: 0.8229 - val_loss: 0.3972 - val_acc: 0.8923
Epoch 3/10
1203/1203 [==============================] - 3s 2ms/step - loss: 0.3549 - acc: 0.9027 - val_loss: 0.2097 - val_acc: 0.9377
Epoch 4/10
1203/1203 [==============================] - 3s 3ms/step - loss: 0.2256 - acc: 0.9377 - val_loss: 0.1505 - val_acc: 0.9562
Epoch 5/10
1203/1203 [==============================] - 3s 3ms/step - loss: 0.1650 - acc: 0.9501 - val_loss: 0.1478 - val_acc: 0.9495
Epoch 6/10
1203/1203 [==============================] - 3s 3ms/step - loss: 0.1498 - acc: 0.9609 - val_loss: 0.0946 - val_acc: 0.9747
Epoch 7/10
1203/1203 [==============================] - 3s 3ms/step - loss: 0.1039 - acc: 0.9726 - val_loss: 0.0726 - val_acc: 0.9832
Epoch 8/10
1203

In [69]:
score = model.evaluate(X_test, y_test)

594/594 [==============================] - 0s 641us/step


In [70]:
score

[0.05817211266318555, 0.9831649833656722]

In [ ]:
model.save('lalala.h5')